trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    containerRegistry: 'ClamAV Container Registry'
    repository: 'clamav'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'